# btrfs-scrub
# Autogenerated from man page /usr/share/man/man8/btrfs-scrub.8.gz
complete -c btrfs-scrub -s c --description 'and.'
complete -c btrfs-scrub -s n --description 'options.  Options.'
complete -c btrfs-scrub -s B --description 'do not background and print scrub statistics when finished.'
complete -c btrfs-scrub -s d --description 'print separate statistics for each device of the filesystem (-B only) at the …'
complete -c btrfs-scrub -s q --description 'be quiet, omit error messages and statistics.'
complete -c btrfs-scrub -s r --description 'run in read-only mode, do not attempt to correct anything, can be run on a re…'
complete -c btrfs-scrub -s R --description 'print raw statistics per-device instead of a summary.'
complete -c btrfs-scrub -s f --description 'force starting new scrub even if a scrub is already running, this can useful …'

