# btrfs-device
# Autogenerated from man page /usr/share/man/man8/btrfs-device.8.gz
complete -c btrfs-device -s K -l nodiscard --description 'do not perform discard (TRIM) by default.'
complete -c btrfs-device -s f -l force --description 'force overwrite of existing filesystem on the given disk(s) remove <device>|<…'
complete -c btrfs-device -l all-devices --description 'or.'
complete -c btrfs-device -s d --description 'are deprecated and kept for backward compatibility.'
complete -c btrfs-device -s z -l reset --description 'Print the stats and reset the values to zero afterwards.'
complete -c btrfs-device -s c -l check --description 'Check if the stats are all zeros and return 0 it this is so.'
complete -c btrfs-device -s b -l raw --description 'raw numbers in bytes, without the B suffix.'
complete -c btrfs-device -s h -l human-readable --description 'print human friendly numbers, base 1024, this is the default.'
complete -c btrfs-device -s H --description 'print human friendly numbers, base 1000.'
complete -c btrfs-device -l iec --description 'select the 1024 base for the following options, according to the IEC standard.'
complete -c btrfs-device -l si --description 'select the 1000 base for the following options, according to the SI standard.'
complete -c btrfs-device -s k -l kbytes --description 'show sizes in KiB, or kB with --si.'
complete -c btrfs-device -s m -l mbytes --description 'show sizes in MiB, or MB with --si.'
complete -c btrfs-device -s g -l gbytes --description 'show sizes in GiB, or GB with --si.'
complete -c btrfs-device -s t -l tbytes --description 'show sizes in TiB, or TB with --si If conflicting options are passed, the las…'

