# btrfs-zero-log
# Autogenerated from man page /usr/share/man/man8/btrfs-zero-log.8.gz
complete -c btrfs-zero-log -s y --description 'assume an answer of yes to all questions.'
complete -c btrfs-zero-log -s v --description 'verbose mode.'
complete -c btrfs-zero-log -s h --description 'help.'

