# btrfs-rescue
# Autogenerated from man page /usr/share/man/man8/btrfs-rescue.8.gz
complete -c btrfs-rescue -s y --description 'assume an answer of yes to all questions.'
complete -c btrfs-rescue -s v --description 'verbose mode.'
complete -c btrfs-rescue -s h --description 'help.'

