# btrfs-replace
# Autogenerated from man page /usr/share/man/man8/btrfs-replace.8.gz
complete -c btrfs-replace -s r --description 'only read from <srcdev> if no other zero-defect mirror exists.'
complete -c btrfs-replace -s f --description 'force using and overwriting <targetdev> even if it looks like it contains a v…'
complete -c btrfs-replace -s B --description 'no background replace.'
complete -c btrfs-replace -s 1 --description 'print once instead of print continuously until the replace operation finishes…'

