# btrfs-quota
# Autogenerated from man page /usr/share/man/man8/btrfs-quota.8.gz
complete -c btrfs-quota -s s --description 'show status of a running rescan operation.'
complete -c btrfs-quota -s w --description 'wait for rescan operation to finish(can be already in progress).'

