# btrfs-receive
# Autogenerated from man page /usr/share/man/man8/btrfs-receive.8.gz
complete -c btrfs-receive -s v --description 'increase verbosity about performed actions, print details about each operatio…'
complete -c btrfs-receive -s f --description 'read the stream from <FILE> instead of stdin,.'
complete -c btrfs-receive -s C -l chroot --description 'confine the process to path using chroot(1).'
complete -c btrfs-receive -s e --description 'terminate after receiving an end cmd marker in the stream.'
complete -c btrfs-receive -s E -l max-errors --description 'terminate as soon as NERR errors occur while stream processing commands from …'
complete -c btrfs-receive -s m --description 'the root mount point of the destination filesystem By default the mountpoint …'
complete -c btrfs-receive -l dump --description 'dump the stream metadata, one line per operation Does not require the path pa…'

