# btrfs-subvolume
# Autogenerated from man page /usr/share/man/man8/btrfs-subvolume.8.gz
complete -c btrfs-subvolume -s i --description 'Add the newly created subvolume to a qgroup.'
complete -c btrfs-subvolume -l commit --description 'options to wait until the operation is safely stored on the device.  Options.'
complete -c btrfs-subvolume -s c -l commit-after --description 'wait for transaction commit at the end of the operation.'
complete -c btrfs-subvolume -s C -l commit-each --description 'wait for transaction commit after deleting each subvolume find-new <subvolume…'
complete -c btrfs-subvolume -s p --description 'is given, then parent <ID> is added to the output between ID and top level.'
complete -c btrfs-subvolume -s a --description 'print all the subvolumes in the filesystem and distinguish between absolute a…'
complete -c btrfs-subvolume -s g --description 'print the generation of the subvolume.'
complete -c btrfs-subvolume -s o --description 'print only subvolumes below specified <path>.'
complete -c btrfs-subvolume -s u --description 'print the UUID of the subvolume.'
complete -c btrfs-subvolume -s q --description 'print the parent uuid of subvolumes (and snapshots).'
complete -c btrfs-subvolume -s R --description 'print the UUID of the sent subvolume, where the subvolume is the result of a …'
complete -c btrfs-subvolume -s t --description 'print the result as a table.'
complete -c btrfs-subvolume -s s --description 'only snapshot subvolumes in the filesystem will be listed.'
complete -c btrfs-subvolume -s r --description 'only readonly subvolumes in the filesystem will be listed.'
complete -c btrfs-subvolume -s G -o ']<value>' --description 'list subvolumes in the filesystem that its generation is >=, < or = value.'
complete -c btrfs-subvolume -l sort --description 'list subvolumes in order by specified items.'

