# btrfsck
# Autogenerated from man page /usr/share/man/man8/btrfsck.8.gz
complete -c btrfsck -s b -l backup --description 'use the first valid set of backup roots stored in the superblock This can be …'
complete -c btrfsck -l super --description 'if some of the superblocks are damaged.'
complete -c btrfsck -l check-data-csum --description 'verify checksums of data blocks This expects that the filesystem is otherwise…'
complete -c btrfsck -l chunk-root --description 'use the given offset bytenr for the chunk tree root.'
complete -c btrfsck -s E -l subvol-extents --description 'show extent state for the given subvolume.'
complete -c btrfsck -s p -l progress --description 'indicate progress at various checking phases.'
complete -c btrfsck -s Q -l qgroup-report --description 'verify qgroup accounting and compare against filesystem accounting.'
complete -c btrfsck -s r -l tree-root --description 'use the given offset bytenr for the tree root.'
complete -c btrfsck -l readonly --description '(default) run in read-only mode, this option exists to calm potential panic w…'
complete -c btrfsck -s s --description 'use superblock\'th superblock copy, valid values are 0, 1 or 2 if the respecti…'
complete -c btrfsck -l clear-space-cache --description 'completely wipe all free space cache of given type For free space cache v1, t…'
complete -c btrfsck -l repair --description 'enable the repair mode and attempt to fix problems where possible.'
complete -c btrfsck -l init-csum-tree --description 'create a new checksum tree and recalculate checksums in all files Note Do not…'
complete -c btrfsck -l init-extent-tree --description 'build the extent tree from scratch Note Do not use unless you know what you\'r…'
complete -c btrfsck -l mode --description 'select mode of operation regarding memory and IO The MODE can be one of origi…'
complete -c btrfsck -l force --description 'allow to work on a mounted filesystem.'

