# btrfs-send
# Autogenerated from man page /usr/share/man/man8/btrfs-send.8.gz
complete -c btrfs-send -s e --description 'if sending multiple subvolumes at once, use the new format and omit the end c…'
complete -c btrfs-send -s p --description 'send an incremental stream from parent to subvol.'
complete -c btrfs-send -s c --description 'use this snapshot as a clone source for an incremental send (multiple allowed…'
complete -c btrfs-send -s f --description 'output is normally written to standard output so it can be, for example, pipe…'
complete -c btrfs-send -l no-data --description 'send in NO_FILE_DATA mode The output stream does not contain any file data an…'
complete -c btrfs-send -s v -l verbose --description 'enable verbose output, print generated commands in a readable form, (each occ…'
complete -c btrfs-send -s q -l quiet --description 'suppress all messages except errors EXIT STATUS btrfs send returns a zero exi…'

