# termite
# Autogenerated from man page /usr/share/man/man1/termite.1.gz
complete -c termite -s h -l help --description 'Display help message.'
complete -c termite -s v -l version --description 'Display version information.'
complete -c termite -s e -l exec --description 'Tell termite start COMMAND instead of the shell.'
complete -c termite -s r -l role --description 'The role to set the termite window to report itself with.'
complete -c termite -s t -l title --description 'Set the termite window\'s title to TITLE.  This disables dynamic titles.'
complete -c termite -s d -l directory --description 'Tell termite to change to DIRECTORY when launching.'
complete -c termite -l geometry --description 'Override the window geometry in pixels.'
complete -c termite -l 'icon\\f8' --description 'Override the window icon name.'
complete -c termite -l hold --description 'Keep termite open after the child process exits.'
complete -c termite -l display --description 'Launch on DISPLAY X display.'
complete -c termite -s c -l config --description 'Specify a path to an alternative config file to use.'
complete -c termite -l name --description 'Set the windows name part of the WM_CLASS property.'
complete -c termite -l icon --description 'Override the window icon name.'
complete -c termite -l help-gtk --description '.'
complete -c termite -l class --description 'Set the windows class part of the WM_CLASS property.'

