# xml2po
# Autogenerated from man page /usr/share/man/man1/xml2po.1.gz
complete -c xml2po -s a -l automatic-tags --description 'Automatically decide if tags are to be considered "final" or not.'
complete -c xml2po -s k -l keep-entities --description 'Don\\*(Aqt expand entities (default).  See also the -e option.'
complete -c xml2po -s e -l expand-all-entities --description 'Expand all entities (including SYSTEM ones).'
complete -c xml2po -s m -l mode --description 'Treat tags as type TYPE (default: docbook).'
complete -c xml2po -s o -l output --description 'Print resulting text (XML while merging translations with "-p" or "-t" option…'
complete -c xml2po -s p -l po-file --description 'Specify a PO FILE containing translation and output XML document with transla…'
complete -c xml2po -s r -l reuse --description 'Specify a translated XML document in FILE with the same structure to generate…'
complete -c xml2po -s t -l translation --description 'Specify a MO file containing translation and output XML document with transla…'
complete -c xml2po -s u -l update-translation --description 'Update a PO file using msgmerge.'
complete -c xml2po -s l -l language --description 'Explicitly set language of the translation.'
complete -c xml2po -s h -l help --description 'Show summary of options.'
complete -c xml2po -s v -l version --description 'Show version of program.'

